CREATE ROLE WM_OPT_PURGE_ROLE NOT IDENTIFIED;

GRANT EXECUTE ON SYS.DBMS_ALERT TO WM_OPT_PURGE_ROLE;
GRANT EXECUTE ON SYS.DBMS_JOB TO WM_OPT_PURGE_ROLE;
GRANT EXECUTE ON SYS.DBMS_LOB TO WM_OPT_PURGE_ROLE;
GRANT EXECUTE ON SYS.DBMS_OUTPUT TO WM_OPT_PURGE_ROLE;
GRANT EXECUTE ON SYS.DBMS_UTILITY TO WM_OPT_PURGE_ROLE;
GRANT EXECUTE ON SYS.PLITBLM TO WM_OPT_PURGE_ROLE;
GRANT EXECUTE ON SYS.UTL_SMTP TO WM_OPT_PURGE_ROLE;
GRANT SELECT ON SYS.V_$PARAMETER TO WM_OPT_PURGE_ROLE;
GRANT WM_OPT_PURGE_ROLE TO WMOPT_MONITORING;
--GRANT WM_OPT_PURGE_ROLE TO WM71_PROCTRACKER_INFRA;
--GRANT WM_OPT_PURGE_ROLE TO WM71_PROCAUDITLOG_INFRA;
--GRANT WM_OPT_PURGE_ROLE TO SYS WITH ADMIN OPTION;

